import JSZip from "jszip";

import {
  ParseError,
  buildParsedDocument,
  type ParsedDocument,
} from "@/server/parsing/types";

/** Decode the five XML entities that may appear in OOXML text runs. */
function decodeXmlEntities(value: string): string {
  return (
    value
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&quot;/g, '"')
      .replace(/&apos;/g, "'")
      .replace(/&#(\d+);/g, (_, code: string) =>
        String.fromCodePoint(Number(code)),
      )
      .replace(/&#x([0-9a-f]+);/gi, (_, code: string) =>
        String.fromCodePoint(parseInt(code, 16)),
      )
      // Ampersand last, so "&amp;lt;" does not become "<".
      .replace(/&amp;/g, "&")
  );
}

/**
 * Pull visible text out of one slide's XML.
 *
 * Slide XML is machine-generated by PowerPoint, so matching `<a:t>` runs is
 * reliable. Paragraph boundaries (`</a:p>`) become newlines so bullet lists
 * survive as separate lines rather than running together.
 */
export function extractSlideText(xml: string): string {
  const withBreaks = xml
    .replace(/<a:br\s*\/>/g, "\n")
    .replace(/<\/a:p>/g, "\n");
  const runs = withBreaks.match(/<a:t[^>]*>[\s\S]*?<\/a:t>|\n/g) ?? [];
  return runs
    .map((run) =>
      run === "\n" ? "\n" : decodeXmlEntities(run.replace(/<[^>]+>/g, "")),
    )
    .join("")
    .replace(/[ \t]+/g, " ")
    .replace(/ *\n */g, "\n")
    .trim();
}

/** Sort slide paths by their numeric suffix so slide10 follows slide9. */
export function sortSlidePaths(paths: string[]): string[] {
  return [...paths].sort((a, b) => {
    const numberOf = (path: string) =>
      Number(/slide(\d+)\.xml$/.exec(path)?.[1] ?? 0);
    return numberOf(a) - numberOf(b);
  });
}

export async function parsePptx(buffer: Buffer): Promise<ParsedDocument> {
  let zip: JSZip;
  try {
    zip = await JSZip.loadAsync(buffer);
  } catch (error) {
    throw new ParseError(
      "This presentation could not be opened. It may be corrupted.",
      "CORRUPT",
      { cause: error },
    );
  }

  const slidePaths = sortSlidePaths(
    Object.keys(zip.files).filter((path) =>
      /^ppt\/slides\/slide\d+\.xml$/.test(path),
    ),
  );
  if (slidePaths.length === 0) {
    throw new ParseError("No slides found in this presentation.", "EMPTY");
  }

  const slideTexts = await Promise.all(
    slidePaths.map(async (path) => {
      const xml = await zip.file(path)!.async("string");
      return extractSlideText(xml);
    }),
  );

  const parsed = buildParsedDocument(slideTexts);
  if (parsed.wordCount === 0) {
    throw new ParseError(
      "These slides contain no readable text — they may be entirely images.",
      "EMPTY",
    );
  }
  return parsed;
}
